config/routes.rb
Rails.application.routes.draw do

root 'pages#home'

get 'about', to: 'pages#about'
resources :articles

get 'signup', to: 'users#new'
resources :users, except: [:new]

get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'

resources :categories

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :article_categories
	has_many :categories, through: :article_categories
	validates :user_id, presence: true
	validates :title, presence: true, length: {minimum: 3, maximum: 50}
	validates :description, presence: true, length: {minimum: 15}
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :article_categories
	has_many :articles, through: :article_categories
	validates :name, presence: true, length: {minimum: 3, maximum: 25}
	validates_uniqueness_of :name
end

app/models/concerns/user.rb
class User < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles, dependent: :destroy
	before_save { self.email = email.downcase }
	validates 	:username, presence: true,
				uniqueness: {case_sensitive: false},
				length: {minimum: 3, maximum:25}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates 	:email, presence: true, length: {maximum: 105},
				uniqueness: {case_sensitive: false}, 
				format: {with: VALID_EMAIL_REGEX}
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  before_filter :set_page_title

  def current_user
  	@current_user  ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end

  def require_user
  	if !logged_in?
  		flash[:danger] = "You must be logged in"
  		redirect_to root_path
  	end
  end

  private

  def set_page_title
    @page_title = "AlphaBlog"
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :set_article, only:[:edit, :update, :show, :destroy]
	before_action :require_user, except:[:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.user = current_user
		if @article.save
			flash[:success] = "Article Created!"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @article.update(article_params)
			flash[:success] = "Article Updated!"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def destroy
		@article.destroy
		flash[:danger] = "Article was deleted"
		redirect_to articles_path
	end

	def show
	end

	private

		def set_article
			@article = Article.find(params[:id])
		end

		def article_params
			params.require(:article).permit(:title, :description, category_ids:[])
		end

		def require_same_user
			if current_user != @article.user and !current_user.admin?
				flash[:danger] = "You can only edit or delete your own articles"
				redirect_to root_path
			end
		end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :require_admin, except: [:index, :show]

	def index
		@categories = Category.paginate(page: params[:page], per_page: 25)
		@page_title = "Categories"
	end

	def show
		@category = Category.find(params[:id])
		@category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
	end

	def new
		@category = Category.new
		@page_title = "New Category"
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
			flash[:success] = "Category updated"
			redirect_to categories_path(@category)
		else
			render 'edit'
		end
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = "Category added"
			redirect_to categories_path
		else
			render 'new'
		end
	end

	private

	def category_params
		params.require(:category).permit(:name)
	end

	def require_admin
		if !logged_in? || (logged_in? and !current_user.admin?)
			flash[:danger] = "Only admins can create categories"
			redirect_to categories_path
		end
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
	def about
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new

	end

	def create 
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "Login successful"
			redirect_to user_path(user)
		else
			flash.now[:danger] = "Try again"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have logged out"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:edit, :update, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	before_action :require_admin, only: [:destroy]

	def index
		@users = User.paginate(page: params[:page], per_page: 5)
	end
	
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = "Welcome to the AlphaBlog #{@user.username}"
			redirect_to user_path(@user)
		else
			render 'new'
		end
	end

	def set_user
		@user = User.find(params[:id])
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:success] = "Your account was successfully updated!"
			redirect_to articles_path
		else
			render 'edit'
		end
	end

	def show
		@user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
	end

	def destroy 
		@user = User.find(params[:id])
		@user.destroy
		flash[:danger] = "User and their articles have been deleted"
		redirect_to users_path
	end

	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

	def require_same_user
		if logged_in? && current_user != @user and !current_user.admin?
			flash[:danger] = "You can only edit your own profile"
			redirect_to root_path
		end
	end

	def require_admin
		if logged_in? and !current_user.admin?
			flash[:danger] = "Only admins can delete user accounts"
			redirect_to root_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options = {size:80})
		size = options[:size]
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end

end

app/views/articles/_article.html.erb
<div class="listing">
	<% obj.each do |article| %>
		<div>
			<article>
				<div class="row">
					<div class="article well well-md">
						<h2><%= link_to article.title, article_path(article) %></h2>
						<p><%= truncate(article.description, length:250) %></p>
						<div class="bottom">
							<% if article.categories.any? %>
								<p>Categories: <%= render article.categories %></p>
							<% end %>
						</div>
					</div>
					<div class="article-info well well-md">
						<ul class="article-owner">
							<li>Author: <%= article.user.username if article.user %></li>
							<li>Created: <%= article.created_at.strftime("%b %d %Y")%></li>
							<li>Updated: <%= article.updated_at.strftime("%b %d %Y")%></li>
						</ul>
						<% if logged_in? && (current_user == article.user || current_user.admin?) %>
							<ul>
								<li><%= link_to "Update", edit_article_path(article), class:"btn btn-xs btn-success" %></li>
								<li><%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-xs btn-danger" %></li>
							</ul>
						<% end %>
					</div>
				</div>
			</article>
		</div>
	<% end %>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="form group">
	<%= form_for @article do |f| %>

		<div class="col-md-8">
			<p>
				<%= f.label :title %><br/>
				<%= f.text_field :title, class: "form-control", placeholder: "Title", autofocus: true %>
			</p>
		</div>
		<div class="col-md-8">
			<p>
				<%= f.label :description %><br/>
				<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Article Content" %>
			</p>
		</div>

		<div class="col-md-8">
			<p>
				<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
					<%= cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
				<% end %>
			</p>
		</div>

		<div class="col-md-8">
			<btn>
				<%= f.submit class: 'btn btn-primary btn-md'%>
			</btn>

			<btn>
				<%= link_to "Cancel", articles_path, class: 'btn btn-primary btn-md' %>
			</btn>
			</div>
		</div>
	<% end %>
</div>

app/views/articles/edit.html.erb
<section class="container">
	<h1>Edit existing article</h1>

	<%= render 'form' %>
</section>

app/views/articles/index.html.erb
<section class="container">
	<h1 align="center">Listing all articles</h1>

	<div class="listing">
		
		<div align="center">
			<%= will_paginate %>
		</div>

		<%= render 'article', obj: @articles %>
	
		<div align="center">
			<%= will_paginate %>
		</div>
	</div>
</section>

app/views/articles/new.html.erb
<section class="container">

	<h1>Create a new article</h1>

	<%= render 'form' %>

</section>

app/views/articles/show.html.erb
<section class="container">
	<h1 style="visibility:hidden; height:1px; margin:0; padding:0;"><%= @article %></h1>
	<div class="listing">
		<article class="post well">
			<h1><%= @article.title %></h1>

			<div class="owner-info">
				<ul>
					<li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
					<li><%= link_to @article.user.username, user_path(@article.user) %></li>
					<li><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></li>
				</ul>
			</div>
			<p><%= @article.description %></p>

			<hr>

			<% if @article.categories.any? %>
				<p>Categories: <%= render @article.categories %></p>
			<% end %>
		</article>

		<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
			<btn><%= link_to "Edit", edit_article_path(@article), class: 'btn btn-primary btn-xs' %></btn>
			<btn><%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "This will delete the current article. Are you sure?"}, class: 'btn btn-danger btn-xs' %></btn>
		<% end %>

		<btn><%= link_to "All Articles", articles_path, class: 'btn btn-success btn-xs' %></btn>
	</div>

</section>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %>&nbsp;</span>

app/views/categories/_form.html.erb
<div class="form group">
	<%= form_for @category do |f| %>

		<div class="col-md-8">
			<p>
				<%= f.label :name %><br/>
				<%= f.text_field :name, class: "form-control", placeholder: "Category Name", autofocus: true %>
			</p>
		</div>
			<div class="col-md-8">
				<btn>
					<%= f.submit class: 'btn btn-primary btn-md'%>
				</btn>

				<btn>
					<%= link_to "Cancel", root_path, class: 'btn btn-primary btn-md' %>
				</btn>
			</div>
		</div>
	<% end %>
</div>

app/views/categories/edit.html.erb
<section class="container">
  <%= render 'shared/errors', obj: @category %>

  <h1>Edit existing article</h1>

  <%= render 'form' %>
</section>

app/views/categories/index.html.erb
<section class="container">
	<h1 align="center">Listing all categories</h1>

	<div align="center">
		<%= will_paginate %>
	</div>

<div class="listing">


	<article>
		<div class="row">

			<% @categories.each do |category| %>
					<div class="well well-sm col-md-3 col-md-offset-1">
						<h2><%= link_to "#{category.name}", category_path(category) %></h2>
						<p><%= pluralize(category.articles.count, "article") %></p>
					</div>
				<% end %>
		</div>
	</article>
</div>

	<div align="center">
		<%= will_paginate %>
	</div>

</section>

app/views/categories/new.html.erb
<%= render 'shared/errors', obj: @category %>

<div class="form group">
	<%= form_for @category do |f| %>

		<div class="col-md-8">
			<p>
				<%= f.label :name %><br/>
				<%= f.text_field :name, class: "form-control", placeholder: "Category Name", autofocus: true %>
			</p>
		</div>
			<div class="col-md-8">
				<btn>
					<%= f.submit class: 'btn btn-primary btn-md'%>
				</btn>

				<btn>
					<%= link_to "Cancel", root_path, class: 'btn btn-primary btn-md' %>
				</btn>
			</div>
		</div>
	<% end %>
</div>

app/views/categories/show.html.erb
<section class="container">
	<h1 align="center"><%= "Category: " + @category.name %></h1>

	<div class="listing">


		<div align="center">
      <% if logged_in? and current_user.admin? %>
          <p><%= link_to "Edit category name", edit_category_path(@category) %></p>
      <% end %>
			<%= will_paginate @category_articles%>
		</div>

		<%= render 'articles/article', obj: @category_articles %>

		<div align="center">
			<%= will_paginate @category_articles %>
		</div>
	</div>
</section>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
		<p>AlphaBlog &copy;2015</p>
		
		<nav>
			<ul>
				<li><%= link_to_unless_current("Home", root_path) %></li>
				<li><%= link_to_unless_current("About", about_path) %></li>
				<li><%= link_to_unless_current("Users", users_path) %></li>
				<li><%= link_to_unless_current("Blog", articles_path) %></li>
			</ul>
		</nav>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>

<div class="container">
	<% unless current_page?('/') %>
	   <div class="logo"><%= link_to_unless_current("ALPHABLOG", root_path) %></div>
	<% else %>
		<h1><%= link_to_unless_current("ALPHABLOG", root_path) %></h1>
	<% end %>

	<form class="navbar-form navbar-right nav-search" role="search">
		<div class="form-group">
			<input type="text" class="form-control" placeholder="Search">
		</div>
		<button type="submit" class="btn btn-default">Submit</button>
	 </form>
     
	<%= render 'layouts/nav' %>
</div>

</header>

app/views/layouts/_messages.html.erb
<div class="col-md-10 col-md-offset-1">
	<% flash.each do |name, msg| %>
		<div class='alert alert-<%="#{name}"%>'>
			<a href="#" class="close" data-dismiss="alert">&#215;</a>
			<%= msg %>
		</div>
	<% end %>
</div>

app/views/layouts/_nav.html.erb
<nav>
	<ul>
		<li><%= link_to_unless_current("Home", root_path) %></li>
		<li><%= link_to_unless_current("About", about_path) %></li>
		<li class="dropdown">
			<a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">AlphaBlog<span class="caret"></span></a>
			<ul class="dropdown-menu">
			<li><%= link_to_unless_current("Articles", articles_path) %></li>
			<li><%= link_to_unless_current("Bloggers", users_path) %></li>
			<li><%= link_to_unless_current "Categories", categories_path %></li>
			</ul>
		</li>
		<% if logged_in? %>
			<li class="dropdown">
				<a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Articles<span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li><%= link_to 'Create New', new_article_path %></li>
					<li><%= link_to 'Your Articles', user_path(current_user) %></li>
				</ul>
			</li>
			<li class="dropdown">
				<a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username if logged_in? %><span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li><%= link_to 'View Profile', user_path(current_user) %></li>
					<li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
					<li><%= link_to 'Logout', logout_path, method: :delete %></li>
				</ul>
			</li>
			<% if logged_in? and current_user.admin? %>
				<li class="dropdown admin">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><%= link_to "Create New Category", new_category_path %></li>
					</ul>
				</li>
			<% end %>
		<% else %>
			<li><%= link_to 'Login', login_path %></li>
			<li><%= link_to 'Sign Up', signup_path %></li>
		<% end %>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog | <%= @page_title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<% unless current_page?('/') %>
   <body class="default">
<% else %>
	<body class="home">
<% end %>
	<div id="wrap">

		<%= render 'layouts/header' %>

		<div id="main" class="eclear-top container">
			
			<%= render 'layouts/messages' %>
			
			<%= yield %>

		</div>
	</div>

	<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<section class="container">
	<article>
		<h1>Gia's About Page</h1>

		<p>
		  This is my about page! It will probably tell you that I'm a front end dev learning Rails.</p>
		</p>

		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eleifend auctor urna in malesuada. Vivamus nisi massa, commodo non sapien eget, maximus luctus ante. Quisque in risus id dui feugiat pretium. Morbi in libero dolor. Donec sit amet lectus quis leo consequat lobortis. Integer condimentum, massa a rhoncus ultrices, turpis lorem ullamcorper lacus, nec venenatis quam augue eu odio. Donec lobortis nulla et mi aliquam, sed tincidunt lectus bibendum. Cras iaculis fermentum mauris, ut aliquam leo ullamcorper in. Curabitur posuere arcu vulputate leo iaculis accumsan. Nunc condimentum augue vitae odio interdum, eget venenatis orci malesuada. Nullam pretium congue semper. Vivamus molestie sagittis nunc, in feugiat ipsum venenatis at. Proin tempor purus a egestas consectetur. Praesent condimentum ante eu consectetur pretium. Etiam sed laoreet magna. Praesent quis pharetra diam, eu rhoncus eros.</p>

		<p>Aliquam non neque nec urna scelerisque fermentum faucibus ut dolor. Phasellus at sodales felis. Morbi sed augue egestas, pellentesque leo nec, iaculis justo. Vestibulum finibus turpis at nulla ornare, eget feugiat orci bibendum. Proin et velit et metus faucibus aliquet. Donec placerat euismod euismod. Vivamus sed hendrerit risus. Donec et mauris in nulla accumsan convallis vitae vel magna. In lacus est, luctus eget venenatis iaculis, consectetur nec orci. Nulla hendrerit libero ut odio efficitur, eget ultricies diam facilisis. In congue tincidunt ipsum, et scelerisque tortor scelerisque vel. Etiam porttitor, libero a finibus tempus, diam metus fringilla metus, ut rhoncus leo ligula non quam.</p>
	</article>
</section>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="container">
	<div class="col-centered col-md-7">
		<p>Welcome to the not-so-one-and-only AlphaBlog!</p>
	</div>
	<% if logged_in? %>
		<btn><%= link_to 'Entrez', articles_path, class: "btn btn-primary btn-md col-md-1 col-md-offset-6" %></btn>
	<% else %>
		<btn><%= link_to 'Sign Up', signup_path, class: "btn btn-primary btn-md col-md-1 col-md-offset-6" %></btn>
	<% end %>
  </div>
</div>

<section class="container">
	<article>
		<h1>This is my AlphaBlog!</h1>
		<h2>It's filled with AlphaBlog goodness.</h2>

		<p>This is the first project for the <a href="https://www.udemy.com/the-complete-ruby-on-rails-developer-course" target="_blank"> The Complete Ruby on Rails Developer Course</a>.  This is generally to scope with a few additions or modifications while playing around.  This is not an accurate representation of any current skill sets.</p>

    <h2>Play around!</h2>
    <p><strong>Demo User</strong></p>
    <ul>
      <li>login: demouser@test.com</li>
      <li>pswd: demouser</li>
    </ul>
    <p><strong>Demo Admin</strong></p>
    <ul>
      <li>login: demoadmin@test.com</li>
      <li>pswd: demoadmin</li>
    </ul>
    <p><strong>Your Own!</strong></p>
    <p>Please feel free to create your own user</p>
	</article>
</section>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="col-md-10">
		<div class="panel panel-danger">
				<div class="panel-heading">
					<h2 class="panel-title">
						<%= pluralize(obj.errors.count, "errors") %> prevented the article from being saved:
					</h2>
					<div class="panel-body">
						<ul>
							<% obj.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="form group">
	<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

		<div class="col-md-8">
			<p>
				<%= f.label :username %><br/>
				<%= f.text_field :username, class: "form-control", placeholder: "Username", autofocus: true %>
			</p>
		</div>
		<div class="col-md-8">
			<p>
				<%= f.label :email %><br/>
				<%= f.email_field :email, class: "form-control", placeholder: "Email" %>
			</p>
		</div>
		<div class="col-md-8">
			<p>
				<%= f.label :password %><br/>
				<%= f.password_field :password, class: "form-control", placeholder: "Password" %>
			</p>
		</div>
			<div class="col-md-8">
				<btn>
					<%= f.submit(@user.new_record? ? "Sign Up" : "Update account", class: 'btn btn-primary btn-md') %>
				</btn>
			</div>
		</div>
	<% end %>
</div>

app/views/users/edit.html.erb
<section class="container">

  <h1>Edit your account</h1>

  <%= render 'form' %>

</section>

app/views/users/index.html.erb
<section>
	<h1>All the AlphaBloggers</h1>

	<%= will_paginate %>

	<% @users.each do |user| %>

		<ul class="show-users  col-md-3">
			<div class="user-block">
				<li class="grav"><%= link_to gravatar_for(user), user_path(user) %></li>
				<li><%= link_to user.username, user_path(user) %></li>
				<li><%= pluralize(user.articles.count, "article") if user.articles %></li>
				<% if logged_in? and current_user.admin? %>
					<% if user.username != "demo admin" && user.username != "demo user" %>
						<li><%= link_to "Delete User", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete this user and their articles?"} %></li>
					<% end %>
				<% end %>
			</div>
		</ul>

	<% end %>

	<%= will_paginate %>
</section>

app/views/users/new.html.erb
<section class="container">

  <h1>Signup for AlphaBlog</h1>

  <%= render 'form' %>

</section>

app/views/users/show.html.erb
<section class="user-profile">

	<div class="user-profile-info">
		<%= gravatar_for @user, size: 150 %>
		<div class="right">
			<h1><%= @user.username %></h1>
		</div>
	</div>

	<div class="user-profile-articles container">
		<h3><%= @user.username %>'s articles</h3>

		<div align="center">
			<%= will_paginate @user_articles %>
		</div>

		<%= render 'articles/article', obj: @user_articles %>

		<div align="center">
			<%= will_paginate @user_articles %>
		</div>
	</div>

</section>